'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("VDB.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property Add() As String
            Get
                Return ResourceManager.GetString("Add", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to d..
        '''</summary>
        Friend Shared ReadOnly Property Days() As String
            Get
                Return ResourceManager.GetString("Days", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure?.
        '''</summary>
        Friend Shared ReadOnly Property DeleteRequest() As String
            Get
                Return ResourceManager.GetString("DeleteRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Director.
        '''</summary>
        Friend Shared ReadOnly Property Director() As String
            Get
                Return ResourceManager.GetString("Director", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disk name can not be empty.
        '''</summary>
        Friend Shared ReadOnly Property ErrorNameIsEmpty() As String
            Get
                Return ResourceManager.GetString("ErrorNameIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disk type can not be empty.
        '''</summary>
        Friend Shared ReadOnly Property ErrorTypeIsEmpty() As String
            Get
                Return ResourceManager.GetString("ErrorTypeIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search....
        '''</summary>
        Friend Shared ReadOnly Property Find() As String
            Get
                Return ResourceManager.GetString("Find", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add disk.
        '''</summary>
        Friend Shared ReadOnly Property FormAddTitle() As String
            Get
                Return ResourceManager.GetString("FormAddTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete disk.
        '''</summary>
        Friend Shared ReadOnly Property FormDeleteTitle() As String
            Get
                Return ResourceManager.GetString("FormDeleteTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit disk.
        '''</summary>
        Friend Shared ReadOnly Property FormEditTitle() As String
            Get
                Return ResourceManager.GetString("FormEditTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find disk.
        '''</summary>
        Friend Shared ReadOnly Property FormFindTitle() As String
            Get
                Return ResourceManager.GetString("FormFindTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Genre.
        '''</summary>
        Friend Shared ReadOnly Property Genre() As String
            Get
                Return ResourceManager.GetString("Genre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Given.
        '''</summary>
        Friend Shared ReadOnly Property Given() As String
            Get
                Return ResourceManager.GetString("Given", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to h..
        '''</summary>
        Friend Shared ReadOnly Property Houres() As String
            Get
                Return ResourceManager.GetString("Houres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter company name.
        '''</summary>
        Friend Shared ReadOnly Property IsCompaniesModified() As String
            Get
                Return ResourceManager.GetString("IsCompaniesModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter debtor name.
        '''</summary>
        Friend Shared ReadOnly Property IsDebtorsModified() As String
            Get
                Return ResourceManager.GetString("IsDebtorsModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter director name.
        '''</summary>
        Friend Shared ReadOnly Property IsDirectorsModified() As String
            Get
                Return ResourceManager.GetString("IsDirectorsModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter genre name.
        '''</summary>
        Friend Shared ReadOnly Property IsGenresModified() As String
            Get
                Return ResourceManager.GetString("IsGenresModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter actor name.
        '''</summary>
        Friend Shared ReadOnly Property IsStarsModified() As String
            Get
                Return ResourceManager.GetString("IsStarsModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter disk type.
        '''</summary>
        Friend Shared ReadOnly Property IsTypesModified() As String
            Get
                Return ResourceManager.GetString("IsTypesModified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length.
        '''</summary>
        Friend Shared ReadOnly Property Length() As String
            Get
                Return ResourceManager.GetString("Length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display information about program author and version.
        '''</summary>
        Friend Shared ReadOnly Property miAboutToolTip() As String
            Get
                Return ResourceManager.GetString("miAboutToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add a new disk in the collection.
        '''</summary>
        Friend Shared ReadOnly Property miAddToolTip() As String
            Get
                Return ResourceManager.GetString("miAddToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display a list of debtors and discs that they are given.
        '''</summary>
        Friend Shared ReadOnly Property miDebtorsToolTip() As String
            Get
                Return ResourceManager.GetString("miDebtorsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove the disc from the collection.
        '''</summary>
        Friend Shared ReadOnly Property miDeleteToolTip() As String
            Get
                Return ResourceManager.GetString("miDeleteToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill the dictionaries.
        '''</summary>
        Friend Shared ReadOnly Property miDictionariesToolTip() As String
            Get
                Return ResourceManager.GetString("miDictionariesToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit disc information.
        '''</summary>
        Friend Shared ReadOnly Property miEditToolTip() As String
            Get
                Return ResourceManager.GetString("miEditToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close application.
        '''</summary>
        Friend Shared ReadOnly Property miExitToolTip() As String
            Get
                Return ResourceManager.GetString("miExitToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find next disk.
        '''</summary>
        Friend Shared ReadOnly Property miFindNextToolTip() As String
            Get
                Return ResourceManager.GetString("miFindNextToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Find disks in collection.
        '''</summary>
        Friend Shared ReadOnly Property miFindToolTip() As String
            Get
                Return ResourceManager.GetString("miFindToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set mark that the disc is given.
        '''</summary>
        Friend Shared ReadOnly Property miGiveToolTip() As String
            Get
                Return ResourceManager.GetString("miGiveToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create new disks collection.
        '''</summary>
        Friend Shared ReadOnly Property miNewToolTip() As String
            Get
                Return ResourceManager.GetString("miNewToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to min.
        '''</summary>
        Friend Shared ReadOnly Property Minutes() As String
            Get
                Return ResourceManager.GetString("Minutes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open file containing disks data.
        '''</summary>
        Friend Shared ReadOnly Property miOpenToolTip() As String
            Get
                Return ResourceManager.GetString("miOpenToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customize program options.
        '''</summary>
        Friend Shared ReadOnly Property miOptionsToolTip() As String
            Get
                Return ResourceManager.GetString("miOptionsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting page parameters.
        '''</summary>
        Friend Shared ReadOnly Property miPageSetupToolTip() As String
            Get
                Return ResourceManager.GetString("miPageSetupToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Preview disks list befor printing.
        '''</summary>
        Friend Shared ReadOnly Property miPreviewToolTip() As String
            Get
                Return ResourceManager.GetString("miPreviewToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print disks list.
        '''</summary>
        Friend Shared ReadOnly Property miPrintToolTip() As String
            Get
                Return ResourceManager.GetString("miPrintToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Deselect that the disk was given.
        '''</summary>
        Friend Shared ReadOnly Property miReturnToolTip() As String
            Get
                Return ResourceManager.GetString("miReturnToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes in other place.
        '''</summary>
        Friend Shared ReadOnly Property miSaveAsToolTip() As String
            Get
                Return ResourceManager.GetString("miSaveAsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes.
        '''</summary>
        Friend Shared ReadOnly Property miSaveToolTip() As String
            Get
                Return ResourceManager.GetString("miSaveToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by company name.
        '''</summary>
        Friend Shared ReadOnly Property miSortCompanyToolTip() As String
            Get
                Return ResourceManager.GetString("miSortCompanyToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by date.
        '''</summary>
        Friend Shared ReadOnly Property miSortDateToolTip() As String
            Get
                Return ResourceManager.GetString("miSortDateToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by directors name.
        '''</summary>
        Friend Shared ReadOnly Property miSortDirectorToolTip() As String
            Get
                Return ResourceManager.GetString("miSortDirectorToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by genre.
        '''</summary>
        Friend Shared ReadOnly Property miSortGenreToolTip() As String
            Get
                Return ResourceManager.GetString("miSortGenreToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by length.
        '''</summary>
        Friend Shared ReadOnly Property miSortLengthToolTip() As String
            Get
                Return ResourceManager.GetString("miSortLengthToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by original name.
        '''</summary>
        Friend Shared ReadOnly Property miSortNameEngToolTip() As String
            Get
                Return ResourceManager.GetString("miSortNameEngToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by name.
        '''</summary>
        Friend Shared ReadOnly Property miSortNameRusToolTip() As String
            Get
                Return ResourceManager.GetString("miSortNameRusToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by rating.
        '''</summary>
        Friend Shared ReadOnly Property miSortRankToolTip() As String
            Get
                Return ResourceManager.GetString("miSortRankToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by file size.
        '''</summary>
        Friend Shared ReadOnly Property miSortSizeToolTip() As String
            Get
                Return ResourceManager.GetString("miSortSizeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by actors name.
        '''</summary>
        Friend Shared ReadOnly Property miSortStarsToolTip() As String
            Get
                Return ResourceManager.GetString("miSortStarsToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by type.
        '''</summary>
        Friend Shared ReadOnly Property miSortTypeToolTip() As String
            Get
                Return ResourceManager.GetString("miSortTypeToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sort disks by year.
        '''</summary>
        Friend Shared ReadOnly Property miSortYearToolTip() As String
            Get
                Return ResourceManager.GetString("miSortYearToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Display collections statistic information.
        '''</summary>
        Friend Shared ReadOnly Property miStatToolTip() As String
            Get
                Return ResourceManager.GetString("miStatToolTip", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property Name() As String
            Get
                Return ResourceManager.GetString("Name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All discs are the owner.
        '''</summary>
        Friend Shared ReadOnly Property NoGiven() As String
            Get
                Return ResourceManager.GetString("NoGiven", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disks not found.
        '''</summary>
        Friend Shared ReadOnly Property NotFound() As String
            Get
                Return ResourceManager.GetString("NotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page.
        '''</summary>
        Friend Shared ReadOnly Property Page() As String
            Get
                Return ResourceManager.GetString("Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready.
        '''</summary>
        Friend Shared ReadOnly Property Ready() As String
            Get
                Return ResourceManager.GetString("Ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure that the disk is returned?.
        '''</summary>
        Friend Shared ReadOnly Property ReturnRequest() As String
            Get
                Return ResourceManager.GetString("ReturnRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All rights reserved..
        '''</summary>
        Friend Shared ReadOnly Property Rights() As String
            Get
                Return ResourceManager.GetString("Rights", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save changes?.
        '''</summary>
        Friend Shared ReadOnly Property SaveRequest() As String
            Get
                Return ResourceManager.GetString("SaveRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sec.
        '''</summary>
        Friend Shared ReadOnly Property Seconds() As String
            Get
                Return ResourceManager.GetString("Seconds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Size.
        '''</summary>
        Friend Shared ReadOnly Property Size() As String
            Get
                Return ResourceManager.GetString("Size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property Total() As String
            Get
                Return ResourceManager.GetString("Total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend Shared ReadOnly Property Year() As String
            Get
                Return ResourceManager.GetString("Year", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
